/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SystemStatus = IDL.Record({
  'tds' : IDL.Nat,
  'pumpState' : IDL.Bool,
  'temperature' : IDL.Int,
  'waterClarity' : IDL.Text,
});
export const Time = IDL.Int;
export const HydroponicsData = IDL.Record({
  'userName' : IDL.Text,
  'plantName' : IDL.Text,
  'systemStatus' : SystemStatus,
  'startDate' : Time,
});

export const idlService = IDL.Service({
  'getHydroponicsData' : IDL.Func([], [HydroponicsData], ['query']),
  'getPlantName' : IDL.Func([], [IDL.Text], ['query']),
  'getStartDate' : IDL.Func([], [Time], ['query']),
  'getSystemStatus' : IDL.Func([], [SystemStatus], ['query']),
  'getUserName' : IDL.Func([], [IDL.Text], ['query']),
  'setPlantName' : IDL.Func([IDL.Text], [], []),
  'setPumpState' : IDL.Func([IDL.Bool], [], []),
  'setStartDate' : IDL.Func([Time], [], []),
  'setTDS' : IDL.Func([IDL.Nat], [], []),
  'setTemperature' : IDL.Func([IDL.Int], [], []),
  'setUserName' : IDL.Func([IDL.Text], [], []),
  'setWaterClarity' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SystemStatus = IDL.Record({
    'tds' : IDL.Nat,
    'pumpState' : IDL.Bool,
    'temperature' : IDL.Int,
    'waterClarity' : IDL.Text,
  });
  const Time = IDL.Int;
  const HydroponicsData = IDL.Record({
    'userName' : IDL.Text,
    'plantName' : IDL.Text,
    'systemStatus' : SystemStatus,
    'startDate' : Time,
  });
  
  return IDL.Service({
    'getHydroponicsData' : IDL.Func([], [HydroponicsData], ['query']),
    'getPlantName' : IDL.Func([], [IDL.Text], ['query']),
    'getStartDate' : IDL.Func([], [Time], ['query']),
    'getSystemStatus' : IDL.Func([], [SystemStatus], ['query']),
    'getUserName' : IDL.Func([], [IDL.Text], ['query']),
    'setPlantName' : IDL.Func([IDL.Text], [], []),
    'setPumpState' : IDL.Func([IDL.Bool], [], []),
    'setStartDate' : IDL.Func([Time], [], []),
    'setTDS' : IDL.Func([IDL.Nat], [], []),
    'setTemperature' : IDL.Func([IDL.Int], [], []),
    'setUserName' : IDL.Func([IDL.Text], [], []),
    'setWaterClarity' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };